# Generated by Django 5.2rc1 on 2025-04-02 13:09

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория тура или экскурсии',
                'verbose_name_plural': 'Категории туров или экскурсий',
            },
        ),
        migrations.CreateModel(
            name='CityDeparture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название города')),
            ],
            options={
                'verbose_name': 'Город отправления',
                'verbose_name_plural': 'Города отправления',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название страны')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('second_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('tel', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU', verbose_name='Телефон')),
                ('email', models.EmailField(default=None, help_text='Пример: user@example.com', max_length=254, verbose_name='Электронная почта')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название тура или экскурсии')),
                ('description', models.TextField(verbose_name='Описание')),
                ('url', models.SlugField(max_length=160, unique=True)),
                ('image', models.ImageField(upload_to='tours/', verbose_name='Изображение')),
                ('price', models.FloatField(default=0.0, help_text='Цена в рублях', verbose_name='Цена')),
                ('duration', models.IntegerField(default=25, help_text='Количество дней тура или экскурсии', null=True, verbose_name='Длительность (дни)')),
                ('max_tickets', models.IntegerField(default=10, help_text='Максимальное количество мест', null=True, verbose_name='Максимальное кол-во мест')),
                ('current_tickets', models.IntegerField(default=10, help_text='Текущее количество мест', null=True, verbose_name='Текущее кол-во мест')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Category', to='tours.category', verbose_name='Категория')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='CityDeparture', to='tours.citydeparture', verbose_name='Город отправления')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='CountryTour', to='tours.country', verbose_name='Страна где проводится тур или экскурсия')),
            ],
            options={
                'verbose_name': 'Тур и Экскурсия',
                'verbose_name_plural': 'Туры и Экскурсии',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_tickets', models.IntegerField(default=1, help_text='Бронирование места', verbose_name='Сколько мест забронировать?')),
                ('tourTitle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_tour', to='tours.tour', verbose_name='Выбранный тур или экскурсия')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_user', to='tours.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Бронирование тура или экскурсии',
                'verbose_name_plural': 'Бронирование туров или экскурсий',
            },
        ),
    ]
