# Generated by Django 5.2rc1 on 2025-04-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='current_tickets',
            field=models.IntegerField(default=10, help_text='Текущее количество мест', null=True, verbose_name='Кол-во занятых мест'),
        ),
    ]
