# Generated by Django 5.2rc1 on 2025-04-02 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_remove_tour_category_tour_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='user',
            new_name='formData',
        ),
    ]
