# Generated by Django 5.2rc1 on 2025-04-02 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_rename_formdata_booking_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='user',
            new_name='formData',
        ),
    ]
