# Generated by Django 5.2rc1 on 2025-04-03 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_rename_user_booking_formdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='tel',
            new_name='phone',
        ),
    ]
