# Generated by Django 5.2rc1 on 2025-04-04 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_rename_tel_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='tours/')),
                ('tour', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='TourImages', to='tours.tour', verbose_name='Дополнительные изображения тура')),
            ],
        ),
    ]
