# Generated by Django 5.1.7 on 2025-04-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_tourimages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='city',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='user',
            name='second_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='surname',
        ),
        migrations.AddField(
            model_name='user',
            name='pasport',
            field=models.IntegerField(default=1, verbose_name='Серия и Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ФИО'),
        ),
    ]
