# Generated by Django 5.1.7 on 2025-04-06 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0009_rename_city_tour_location_remove_user_second_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pasport',
            new_name='passport',
        ),
    ]
