# Generated by Django 5.2rc1 on 2025-04-07 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0010_rename_pasport_user_passport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='passport',
        ),
        migrations.AddField(
            model_name='user',
            name='number',
            field=models.IntegerField(default=123456, verbose_name='Номер паспорта'),
        ),
        migrations.AddField(
            model_name='user',
            name='serial',
            field=models.IntegerField(default=1234, verbose_name='Серия паспорта'),
        ),
    ]
