# Generated by Django 5.2rc1 on 2025-04-17 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0011_remove_user_passport_user_number_user_serial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='location',
            new_name='city',
        ),
    ]
