# Generated by Django 5.2rc1 on 2025-04-21 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0012_rename_location_tour_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='city',
            new_name='location',
        ),
    ]
